[project]
site_name = "算玄阁"
site_description = "聪明的穷举一切可能！"
site_author = "palemoky"
site_url = "https://algo.palemoky.com"
repo_url = "https://github.com/palemoky/leetcode"
repo_name = "palemoky/leetcode"
edit_uri = "edit/main/docs/"
copyright = "Copyright &copy; <span id='copyright-year'>2026</span> Palemoky"

extra_javascript = [
  "assets/javascripts/mathjax.js",
  "https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js",
  "assets/javascripts/width-toggle.js"
]

extra_css = [
  "assets/stylesheets/extra.css"
]

nav = [
  { "首页" = "index.md" },
  { "数据结构" = [
      { "数据结构概览" = "data_structures/README.md" },
      { "数组" = "data_structures/array/README.md" },
      { "栈" = "data_structures/stack/README.md" },
      { "队列" = "data_structures/queue/README.md" },
      { "哈希表" = "data_structures/hash_table/README.md" },
      { "链表" = "data_structures/linked_list/README.md" },
      { "树" = "data_structures/tree/README.md" },
      { "图" = "data_structures/graph/README.md" },
      { "字典树" = "data_structures/trie/README.md" },
      { "并查集" = "data_structures/union_find/README.md" }
  ]},
  { "算法" = [
      { "算法概览" = "algorithms/README.md" },
      { "递归算法" = "algorithms/recursion/README.md" },
      { "遍历算法" = "algorithms/traversal/README.md" },
      { "动态规划" = "algorithms/dynamic_programming/README.md" },
      { "回溯算法" = "algorithms/backtracking/README.md" },
      { "排序算法" = "algorithms/sorting/README.md" },
      { "贪心算法" = "algorithms/greedy/README.md" }
  ]},
  { "算法模式" = [
      { "模式概览" = "patterns/README.md" },
      { "双指针" = "patterns/two_pointers/README.md" },
      { "滑动窗口" = "patterns/sliding_window/README.md" },
      { "二分查找" = "patterns/binary_search/README.md" },
      { "前缀和" = "patterns/prefix_sum/README.md" },
      { "差分数组" = "patterns/difference_array/README.md" },
      { "单调栈" = "patterns/monotonic_stack/README.md" },
      { "N数之和" = "patterns/n_sum/README.md" },
      { "N次方问题" = "patterns/power_of_n/README.md" },
      { "位运算" = "patterns/bit_manipulation/README.md" },
      { "数学模拟" = "patterns/elementary_math_simulation/README.md" }
  ]},
  { "数学" = [
      { "数学概览" = "math/README.md" },
      { "最大公约数与最小公倍数" = "math/GCD&LCM/README.md" },
      { "矩阵运算" = "math/matrix/README.md" }
  ]},
  { "语言" = [
      { "编程语言概览" = "lang/README.md" },
      { "Go" = "lang/go/README.md" },
      { "Python" = "lang/python/README.md" }
  ]},
  { "刷题清单" = [
      { "刷题清单" = "checklist/README.md" },
      { "Go" = "checklist/go/README.md" },
      { "Python" = "checklist/python/README.md" }
  ]}
]

[project.theme]
variant = "modern"
custom_dir = "docs/overrides"
name = "material"
language = "zh"
favicon = "assets/images/logo.png"
logo = "assets/images/logo.png"
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.tooltips",
  "navigation.expand",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.tabs",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "search.share",
  "search.suggest",
  "toc.follow"
]

icon = { repo = "fontawesome/brands/github", edit = "lucide/file-edit" }
palette = [
  { scheme = "default", accent = "blue", toggle.icon = "lucide/sun", toggle.name = "Switch to dark mode" },
  { scheme = "slate", accent = "cyan", toggle.icon = "lucide/moon", toggle.name = "Switch to light mode" },
]

[project.plugins.search]
lang = ["zh", "en"]


[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
tables = {}

toc.permalink = true
toc.toc_depth = 4
toc.slugify = { object = "pymdownx.slugs.slugify", kwds = { case = "lower" } }

[project.markdown_extensions.pymdownx]
arithmatex.generic = true
betterem.smart_enable = "none"
"blocks.admonition" = {} # Support GitHub style admonitions
caret = {}
details = {}
emoji = {}

highlight.anchor_linenums = true
highlight.line_spans = "__span"
highlight.pygments_lang_class = true
highlight.linenums = true

inlinehilite = {}
keys = {}
mark = {}
smartsymbols = {}

superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

tabbed.alternate_style = true
tasklist.custom_checkbox = true
tilde = {}

[project.markdown_extensions.zensical.extensions.glightbox]

[project.extra]
generator = false
social = [
  { icon = "fontawesome/brands/github", link = "https://github.com/palemoky" },
  { icon = "fontawesome/solid/book", link = "https://readings.palemoky.com" },
  { icon = "fontawesome/solid/feather", link = "https://poetry.palemoky.com" },
  # { icon = "fontawesome/solid/feather-pointed", link = "https://blog.palemoky.com" }
]
