#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT" || exit 1

langs="go python rust"
dirs="go python rust"
tests=("go test ./... && go test -cover ./..." "pytest" "cargo test")

i=0
for lang in $langs; do
    if git diff --cached --name-only | grep "\.${lang}$" > /dev/null; then
        dir=$(echo $dirs | cut -d' ' -f$((i+1)))
        test_cmd=$(echo ${tests[$i]})
        cd ./$dir && eval "$test_cmd" && cd -
    fi
    i=$((i+1))
done
