#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT" || exit 1

langs="go python rust"
dirs="go python rust"
fmts=("go fmt ./..." "black ." "cargo fmt")

i=0
for lang in $langs; do
    if git diff --cached --name-only | grep "\.${lang}$" > /dev/null; then
        dir=$(echo $dirs | cut -d' ' -f$((i+1)))
        fmt_cmd=$(echo ${fmts[$i]})
        cd ./$dir && eval "$fmt_cmd" && cd -
        git ls-files --modified | grep "\.${lang}$" | xargs git add
        echo "Some $lang files were reformatted and re-staged. Please review the changes and commit again."
    fi
    i=$((i+1))
done
